#!/usr/bin/env sh
ZSHMQ_EMBEDDED=1
ZSHMQ_VERSION=0.0.3

# shellcheck shell=sh disable=SC2016,SC2317
# [getoptions] License: Creative Commons Zero v1.0 Universal
getoptions() {
	_error="" _on=1 _no="" _export="" _plus="" _mode="" _alt="" _rest="" _def=""
	_flags="" _nflags="" _opts="" _help="" _abbr="" _cmds="" _init=@empty IFS=" "
	[ $# -lt 2 ] && set -- "${1:?No parser definition}" -
	[ "$2" = - ] && _def=getoptions_parse

	i="					"
	while eval "_${#i}() { echo \"$i\$@\"; }" && [ "$i" ]; do i=${i#?}; done

	quote() {
		q="$2'" r=""
		while [ "$q" ]; do r="$r${q%%\'*}'\''" && q=${q#*\'}; done
		q="'${r%????}'" && q=${q#\'\'} && q=${q%\'\'}
		eval "$1=\${q:-\"''\"}"
	}
	code() {
		[ "${1#:}" = "$1" ] && c=3 || c=4
		eval "[ ! \${$c:+x} ] || $2 \"\$$c\""
	}
	sw() { sw="$sw${sw:+|}$1"; }
	kv() { eval "${2-}${1%%:*}=\${1#*:}"; }
	loop() { [ $# -gt 1 ] && [ "$2" != -- ]; }

	invoke() { eval '"_$@"'; }
	prehook() { invoke "$@"; }
	for i in setup flag param option disp msg; do
		eval "$i() { prehook $i \"\$@\"; }"
	done

	args() {
		on=$_on no=$_no export=$_export init=$_init _hasarg=$1 && shift
		while loop "$@" && shift; do
			case $1 in
				-?) [ "$_hasarg" ] && _opts="$_opts${1#-}" || _flags="$_flags${1#-}" ;;
				+?) _plus=1 _nflags="$_nflags${1#+}" ;;
				[!-+]*) kv "$1"
			esac
		done
	}
	defvar() {
		case $init in
			@none) : ;;
			@export) code "$1" _0 "export $1" ;;
			@empty) code "$1" _0 "${export:+export }$1=''" ;;
			@unset) code "$1" _0 "unset $1 ||:" "unset OPTARG ||:; ${1#:}" ;;
			*)
				case $init in @*) eval "init=\"=\${${init#@}}\""; esac
				case $init in [!=]*) _0 "$init"; return 0; esac
				quote init "${init#=}"
				code "$1" _0 "${export:+export }$1=$init" "OPTARG=$init; ${1#:}"
		esac
	}
	_setup() {
		[ "${1#-}" ] && _rest=$1
		while loop "$@" && shift; do kv "$1" _; done
	}
	_flag() { args "" "$@"; defvar "$@"; }
	_param() { args 1 "$@"; defvar "$@"; }
	_option() { args 1 "$@"; defvar "$@"; }
	_disp() { args "" "$@"; }
	_msg() { args "" _ "$@"; }

	cmd() { _mode=@ _cmds="$_cmds${_cmds:+|}'$1'"; }
	"$@"
	cmd() { :; }
	_0 "${_rest:?}=''"

	_0 "${_def:-$2}() {"
	_1 'OPTIND=$(($#+1))'
	_1 "while OPTARG= && [ \"\${$_rest}\" != x ] && [ \$# -gt 0 ]; do"
	[ "$_abbr" ] && getoptions_abbr "$@"

	args() {
		sw="" validate="" pattern="" counter="" on=$_on no=$_no export=$_export
		while loop "$@" && shift; do
			case $1 in
				--\{no-\}*) i=${1#--?no-?}; sw "'--$i'|'--no-$i'" ;;
				--with\{out\}-*) i=${1#--*-}; sw "'--with-$i'|'--without-$i'" ;;
				[-+]? | --*) sw "'$1'" ;;
				*) kv "$1"
			esac
		done
		quote on "$on"
		quote no "$no"
	}
	setup() { :; }
	_flag() {
		args "$@"
		[ "$counter" ] && on=1 no=-1 v="\$((\${$1:-0}+\$OPTARG))" || v=""
		_3 "$sw)"
		_4 '[ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break'
		_4 "eval '[ \${OPTARG+x} ] &&:' && OPTARG=$on || OPTARG=$no"
		valid "$1" "${v:-\$OPTARG}"
		_4 ";;"
	}
	_param() {
		args "$@"
		_3 "$sw)"
		_4 '[ $# -le 1 ] && set "required" "$1" && break'
		_4 'OPTARG=$2'
		valid "$1" '$OPTARG'
		_4 "shift ;;"
	}
	_option() {
		args "$@"
		_3 "$sw)"
		_4 'set -- "$1" "$@"'
		_4 '[ ${OPTARG+x} ] && {'
		_5 'case $1 in --no-*|--without-*) set "noarg" "${1%%\=*}"; break; esac'
		_5 '[ "${OPTARG:-}" ] && { shift; OPTARG=$2; } ||' "OPTARG=$on"
		_4 "} || OPTARG=$no"
		valid "$1" '$OPTARG'
		_4 "shift ;;"
	}
	valid() {
		set -- "$validate" "$pattern" "$1" "$2"
		[ "$1" ] && _4 "$1 || { set -- ${1%% *}:\$? \"\$1\" $1; break; }"
		[ "$2" ] && {
			_4 "case \$OPTARG in $2) ;;"
			_5 '*) set "pattern:'"$2"'" "$1"; break'
			_4 "esac"
		}
		code "$3" _4 "${export:+export }$3=\"$4\"" "${3#:}"
	}
	_disp() {
		args "$@"
		_3 "$sw)"
		code "$1" _4 "echo \"\${$1}\"" "${1#:}"
		_4 "exit 0 ;;"
	}
	_msg() { :; }

	[ "$_alt" ] && _2 'case $1 in -[!-]?*) set -- "-$@"; esac'
	_2 'case $1 in'
	_wa() { _4 "eval 'set -- $1' \${1+'\"\$@\"'}"; }
	_op() {
		_3 "$1) OPTARG=\$1; shift"
		_wa '"${OPTARG%"${OPTARG#??}"}" '"$2"'"${OPTARG#??}"'
		_4 "${4:-}$3"
	}
	_3 '--?*=*) OPTARG=$1; shift'
	_wa '"${OPTARG%%\=*}" "${OPTARG#*\=}"'
	_4 ";;"
	_3 "--no-*|--without-*) unset OPTARG ;;"
	[ "$_alt" ] || {
		[ "$_opts" ] && _op "-[$_opts]?*" "" ";;"
		[ ! "$_flags" ] || _op "-[$_flags]?*" - "OPTARG= ;;" \
			'case $2 in --*) set -- "$1" unknown "$2" && '"$_rest=x; esac;"
	}
	[ "$_plus" ] && {
		[ "$_nflags" ] && _op "+[$_nflags]?*" + "unset OPTARG ;;"
		_3 "+*) unset OPTARG ;;"
	}
	_2 "esac"
	_2 'case $1 in'
	"$@"
	rest() {
		_4 'while [ $# -gt 0 ]; do'
		_5 "$_rest=\"\${$_rest}" '\"\${$(($OPTIND-$#))}\""'
		_5 "shift"
		_4 "done"
		_4 "break ;;"
	}
	_3 "--)"
	[ "$_mode" = @ ] || _4 "shift"
	rest
	_3 "[-${_plus:++}]?*)" 'set "unknown" "$1"; break ;;'
	_3 "*)"
	case $_mode in
		@)
			_4 "case \$1 in ${_cmds:-*}) ;;"
			_5 '*) set "notcmd" "$1"; break'
			_4 "esac"
			rest ;;
		+) rest ;;
		*) _4 "$_rest=\"\${$_rest}" '\"\${$(($OPTIND-$#))}\""'
	esac
	_2 "esac"
	_2 "shift"
	_1 "done"
	_1 '[ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }'
	_1 'case $1 in'
	_2 'unknown) set "Unrecognized option: $2" "$@" ;;'
	_2 'noarg) set "Does not allow an argument: $2" "$@" ;;'
	_2 'required) set "Requires an argument: $2" "$@" ;;'
	_2 'pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;'
	_2 'notcmd) set "Not a command: $2" "$@" ;;'
	_2 '*) set "Validation error ($1): $2" "$@"'
	_1 "esac"
	[ "$_error" ] && _1 "$_error" '"$@" >&2 || exit $?'
	_1 'echo "$1" >&2'
	_1 "exit 1"
	_0 "}"

	[ "$_help" ] && eval "shift 2; getoptions_help $1 $_help" ${3+'"$@"'}
	[ "$_def" ] && _0 "eval $_def \${1+'\"\$@\"'}; eval set -- \"\${$_rest}\""
	_0 "# Do not execute" # exit 1
}

# shellcheck shell=sh disable=SC2016,SC2317
# [getoptions_abbr] License: Creative Commons Zero v1.0 Universal
getoptions_abbr() {
	abbr() {
		_3 "case '$1' in"
		_4 '"$1") OPTARG=; break ;;'
		_4 '$1*) OPTARG="$OPTARG '"$1"'"'
		_3 "esac"
	}
	args() {
		abbr=1
		shift
		[ $# -gt 0 ] || return 0
		for i in "$@"; do
			case $i in
				--) break ;;
				[!-+]*) eval "${i%%:*}=\${i#*:}"
			esac
		done
		[ "$abbr" ] || return 0

		for i in "$@"; do
			case $i in
				--) break ;;
				--\{no-\}*) abbr "--${i#--\{no-\}}"; abbr "--no-${i#--\{no-\}}" ;;
				--*) abbr "$i"
			esac
		done
	}
	setup() { :; }
	for i in flag param option disp; do
		eval "_$i()" '{ args "$@"; }'
	done
	msg() { :; }
	_2 'set -- "${1%%\=*}" "${1#*\=}" "$@"'
	[ "$_alt" ] && _2 'case $1 in -[!-]?*) set -- "-$@"; esac'
	_2 'while [ ${#1} -gt 2 ]; do'
	_3 'case $1 in (*[!a-zA-Z0-9_-]*) break; esac'
	"$@"
	_3 "break"
	_2 "done"
	_2 'case ${OPTARG# } in'
	_3 "*\ *)"
	_4 'eval "set -- $OPTARG $1 $OPTARG"'
	_4 'OPTIND=$((($#+1)/2)) OPTARG=$1; shift'
	_4 'while [ $# -gt "$OPTIND" ]; do OPTARG="$OPTARG, $1"; shift; done'
	_4 'set "Ambiguous option: $1 (could be $OPTARG)" ambiguous "$@"'
	[ "$_error" ] && _4 "$_error" '"$@" >&2 || exit $?'
	_4 'echo "$1" >&2'
	_4 "exit 1 ;;"
	_3 "?*)"
	_4 '[ "$2" = "$3" ] || OPTARG="$OPTARG=$2"'
	_4 "shift 3; eval 'set -- \"\${OPTARG# }\"' \${1+'\"\$@\"'}; OPTARG= ;;"
	_3 "*) shift 2"
	_2 "esac"
}

# shellcheck shell=sh disable=SC2016,SC2317
# [getoptions_help] License: Creative Commons Zero v1.0 Universal
getoptions_help() {
	_width="30,12" _plus="" _leading="  "

	pad() { p=$2; while [ ${#p} -lt "$3" ]; do p="$p "; done; eval "$1=\$p"; }
	kv() { eval "${2-}${1%%:*}=\${1#*:}"; }
	sw() { pad sw "$sw${sw:+, }" "$1"; sw="$sw$2"; }

	args() {
		_type=$1 var=${2%% *} sw="" label="" hidden="" && shift 2
		while [ $# -gt 0 ] && i=$1 && shift && [ "$i" != -- ]; do
			case $i in
				--*) sw $((${_plus:+4}+4)) "$i" ;;
				-?) sw 0 "$i" ;;
				+?) [ ! "$_plus" ] || sw 4 "$i" ;;
				*) [ "$_type" = setup ] && kv "$i" _; kv "$i"
			esac
		done
		[ "$hidden" ] && return 0 || len=${_width%,*}

		[ "$label" ] || case $_type in
			setup | msg) label="" len=0 ;;
			flag | disp) label="$sw " ;;
			param) label="$sw $var " ;;
			option) label="${sw}[=$var] "
		esac
		[ "$_type" = cmd ] && label=${label:-$var } len=${_width#*,}
		pad label "${label:+$_leading}$label" "$len"
		[ ${#label} -le "$len" ] && [ $# -gt 0 ] && label="$label$1" && shift
		echo "$label"
		pad label "" "$len"
		[ $# -gt 0 ] || return 0
		for i in "$@"; do echo "$label$i"; done
	}

	for i in setup flag param option disp "msg -" cmd; do
		eval "${i% *}() { args $i \"\$@\"; }"
	done

	echo "$2() {"
	echo "cat<<'GETOPTIONSHERE'"
	"$@"
	echo "GETOPTIONSHERE"
	echo "}"
}

# shellcheck shell=sh

: ${ZSHMQ_COMMAND_REGISTRY:=}

zshmq_register_command() {
  cmd=$1
  case " ${ZSHMQ_COMMAND_REGISTRY} " in
    *" ${cmd} "*)
      :
      ;;
    *)
      if [ -n "${ZSHMQ_COMMAND_REGISTRY}" ]; then
        ZSHMQ_COMMAND_REGISTRY="${ZSHMQ_COMMAND_REGISTRY} ${cmd}"
      else
        ZSHMQ_COMMAND_REGISTRY="${cmd}"
      fi
      ;;
  esac
}

zshmq_command_file() {
  command=$1
  if [ -z "${ZSHMQ_ROOT:-}" ]; then
    return 1
  fi
  file="${ZSHMQ_ROOT}/lib/${command}.sh"
  if [ -f "$file" ]; then
    printf '%s\n' "$file"
    return 0
  fi
  return 1
}

zshmq_command_metadata() {
  command=$1
  key=$2
  file=$(zshmq_command_file "$command") || return 1
  sed -n "s/^[[:space:]]*# *@${key}:[[:space:]]*//p" "$file"
}

zshmq_registered_commands() {
  for cmd in $ZSHMQ_COMMAND_REGISTRY; do
    [ -n "$cmd" ] && printf '%s\n' "$cmd"
  done
}

zshmq_command_summary() {
  command=$1
  summary=$(zshmq_command_metadata "$command" summary | sed -n '1p')
  if [ -n "$summary" ]; then
    printf '%s\n' "$summary"
  else
    printf '%s\n' 'Undocumented command.'
  fi
}

zshmq_parser_defaults() {
  usage_text=${ZSHMQ_PARSER_USAGE:-"zshmq <command>"}
  setup REST help:usage -- "Usage: ${usage_text}" ''
  msg -- 'Options:'
  flag ZSHMQ_HELP -h --help -- 'Display command documentation and exit.'
  flag ZSHMQ_DEBUG -d --debug -- 'Enable DEBUG log level.'
  flag ZSHMQ_TRACE -t --trace -- 'Enable TRACE log level.'
}

zshmq_print_command_help() {
  command=$1
  usage=$(zshmq_command_metadata "$command" usage | sed -n '1p')
  if [ -z "$usage" ]; then
    usage="zshmq $command"
  fi

  printf 'Command: %s\n' "$command"
  printf 'Usage: %s\n' "$usage"
  printf '\n'

  description=$(zshmq_command_metadata "$command" description)
  if [ -n "$description" ]; then
    printf '%s\n' "$description"
    printf '\n'
  else
    summary=$(zshmq_command_metadata "$command" summary | sed -n '1p')
    if [ -n "$summary" ]; then
      printf '%s\n\n' "$summary"
    fi
  fi

  options=$(zshmq_command_metadata "$command" option)
  if [ -n "$options" ]; then
    printf 'Options:\n'
    zshmq_command_metadata "$command" option | while IFS= read -r line; do
      printf '  %s\n' "$line"
    done
  fi
}

zshmq_eval_parser() {
  command=$1
  parser_fn=$2
  shift 2
  ZSHMQ_PARSER_USAGE=$(zshmq_command_metadata "$command" usage | sed -n '1p')
  if [ -z "$ZSHMQ_PARSER_USAGE" ]; then
    ZSHMQ_PARSER_USAGE="zshmq $command"
  fi
  unset ZSHMQ_HELP ||:
  unset ZSHMQ_DEBUG ||:
  unset ZSHMQ_TRACE ||:
  # shellcheck disable=SC2039
  eval "$(getoptions $parser_fn zshmq_parse_runner)" || return 1
  zshmq_parse_runner "$@"
  ZSHMQ_REST=$REST
  if [ "${ZSHMQ_TRACE:-0}" = "1" ]; then
    ZSHMQ_LOG_LEVEL=TRACE
  elif [ "${ZSHMQ_DEBUG:-0}" = "1" ]; then
    ZSHMQ_LOG_LEVEL=DEBUG
  fi
  : "${ZSHMQ_LOG_LEVEL:=INFO}"
  export ZSHMQ_LOG_LEVEL
  if [ "${ZSHMQ_HELP:-0}" = "1" ]; then
    zshmq_print_command_help "$command"
    return 2
  fi
  return 0
}

# shellcheck shell=sh

ZSHMQ_LOG_LEVEL=${ZSHMQ_LOG_LEVEL:-INFO}

zshmq_log_level_value() {
  level=$(printf '%s' "$1" | tr '[:lower:]' '[:upper:]')
  case $level in
    TRACE) printf '%s\n' 0 ;;
    DEBUG) printf '%s\n' 10 ;;
    INFO) printf '%s\n' 20 ;;
    WARN) printf '%s\n' 30 ;;
    ERROR) printf '%s\n' 40 ;;
    FATAL) printf '%s\n' 50 ;;
    *) printf '%s\n' 20 ;;
  esac
}

zshmq_log_threshold_value() {
  zshmq_log_level_value "${ZSHMQ_LOG_LEVEL:-INFO}"
}

zshmq_log_should_emit() {
  level_value=$(zshmq_log_level_value "$1")
  threshold=$(zshmq_log_threshold_value)
  [ "$level_value" -ge "$threshold" ]
}

zshmq_log_timestamp() {
  date '+%Y-%m-%d %H:%M:%S'
}

zshmq_log() {
  level=${1:-INFO}
  shift || :
  normalized=$(printf '%s' "$level" | tr '[:lower:]' '[:upper:]')
  zshmq_log_should_emit "$normalized" || return 0

  if [ $# -gt 0 ]; then
    format=$1
    shift || :
    if [ $# -gt 0 ]; then
      message=$(printf "$format" "$@")
    else
      message=$format
    fi
  else
    message=
  fi

  timestamp=$(zshmq_log_timestamp)
  printf '%s [%s] %s\n' "$timestamp" "$normalized" "$message" >&2
}

zshmq_log_trace() {
  zshmq_log TRACE "$@"
}

zshmq_log_debug() {
  zshmq_log DEBUG "$@"
}

zshmq_log_info() {
  zshmq_log INFO "$@"
}

zshmq_log_warn() {
  zshmq_log WARN "$@"
}

zshmq_log_error() {
  zshmq_log ERROR "$@"
}

zshmq_log_fatal() {
  zshmq_log FATAL "$@"
}

# shellcheck shell=sh

#/**
# ctx - Manage the runtime directory used by zshmq commands.
# @usage: zshmq ctx <command> [options]
# @summary: Manage the runtime directory (default: /tmp/zshmq).
# @description: Provides subcommands to initialise (`ctx new`) or delete (`ctx destroy`) the runtime directory where FIFOs, state files, and dispatcher metadata live.
# @option: -p, --path PATH    Runtime directory to target (defaults to $ZSHMQ_CTX_ROOT or /tmp/zshmq).
# @option: -d, --debug        Enable DEBUG log level.
# @option: -t, --trace        Enable TRACE log level.
# @option: -h, --help         Display command documentation and exit.
#*/

ctx_print_usage() {
  printf '%s\n' 'Usage: zshmq ctx <command> [options]'
  printf '%s\n' ''
  printf '%s\n' 'Commands:'
  printf '  new      Initialise the runtime directory\n'
  printf '  destroy  Remove the runtime directory (use --force to ignore leftovers)\n'
}

ctx_resolve_target() {
  target=$1

  if [ -z "$target" ]; then
    zshmq_log_error 'ctx: target path is empty'
    return 1
  fi

  case $target in
    /|'')
      zshmq_log_error 'ctx: refusing to operate on root directory'
      return 1
      ;;
  esac

  printf '%s\n' "${target%/}"
}

ctx_new_impl() {
  runtime_root=$1

  if [ ! -d "$runtime_root" ]; then
    mkdir -p "$runtime_root"
  fi

  zshmq_log_debug 'ctx new: initialised runtime=%s' "$runtime_root"
}

ctx_destroy_impl() {
  runtime_root=$1
  force=$2

  if [ ! -d "$runtime_root" ]; then
    zshmq_log_debug 'ctx destroy: runtime not found (%s)' "$runtime_root"
    return 0
  fi

  if [ "$force" = "1" ]; then
    rm -rf "$runtime_root"
    zshmq_log_debug 'ctx destroy: forcefully removed runtime=%s' "$runtime_root"
    return 0
  fi

  pid_path=${ZSHMQ_DISPATCH_PID:-${runtime_root}/bus.pid}
  if [ -f "$pid_path" ]; then
    rm -f "$pid_path"
    zshmq_log_debug 'ctx destroy: removed pid=%s' "$pid_path"
  fi

  remaining=$(find "$runtime_root" -mindepth 1 -maxdepth 1 -not -name '.' -not -name '..' -print -quit 2>/dev/null || :)
  if [ -n "${remaining:-}" ]; then
    zshmq_log_error 'ctx destroy: runtime contains files; re-run with --force to remove %s' "$runtime_root"
    return 1
  fi

  if ! rmdir "$runtime_root" 2>/dev/null; then
    zshmq_log_error 'ctx destroy: failed to remove directory %s' "$runtime_root"
    return 1
  fi

  zshmq_log_debug 'ctx destroy: cleaned runtime=%s' "$runtime_root"
}

ctx() {
  set -eu

  log_level=${ZSHMQ_LOG_LEVEL:-INFO}
  target_path=${ZSHMQ_CTX_ROOT:-/tmp/zshmq}

  while [ $# -gt 0 ]; do
    case $1 in
      -p|--path)
        shift
        if [ $# -eq 0 ]; then
          zshmq_log_error 'ctx: --path requires a value'
          return 1
        fi
        target_path=$1
        ;;
      -p=*|--path=*)
        target_path=${1#*=}
        ;;
      -d|--debug)
        log_level=DEBUG
        ;;
      -t|--trace)
        log_level=TRACE
        ;;
      -h|--help|help)
        ctx_print_usage
        return 0
        ;;
      --)
        shift
        break
        ;;
      -*)
        zshmq_log_error 'ctx: unexpected option -- %s' "$1"
        return 1
        ;;
      *)
        break
        ;;
    esac
    shift || :
  done

  export ZSHMQ_LOG_LEVEL=$log_level

  if [ $# -eq 0 ]; then
    ctx_print_usage
    return 1
  fi

  subcommand=$1
  shift

  runtime_root=$(ctx_resolve_target "$target_path") || return 1

  case $subcommand in
    new)
      if [ $# -gt 0 ]; then
        zshmq_log_error 'ctx new: unexpected argument -- %s' "$1"
        return 1
      fi
      ctx_new_impl "$runtime_root"
      ;;
    destroy)
      force=0
      while [ $# -gt 0 ]; do
        case $1 in
          -f|--force)
            force=1
            ;;
          -h|--help|help)
            ctx_print_usage
            return 0
            ;;
          --)
            shift
            break
            ;;
          -*)
            zshmq_log_error 'ctx destroy: unexpected option -- %s' "$1"
            return 1
            ;;
          *)
            zshmq_log_error 'ctx destroy: unexpected argument -- %s' "$1"
            return 1
            ;;
        esac
        shift || :
      done

      if [ $# -gt 0 ]; then
        zshmq_log_error 'ctx destroy: unexpected argument -- %s' "$1"
        return 1
      fi

      ctx_destroy_impl "$runtime_root" "$force"
      ;;
    *)
      zshmq_log_error 'ctx: unknown command -- %s' "$subcommand"
      ctx_print_usage
      return 1
      ;;
  esac
}

if command -v zshmq_register_command >/dev/null 2>&1; then
  zshmq_register_command ctx
fi

# shellcheck shell=sh

#/**
# send - Publish a message to the zshmq dispatcher.
# @usage: zshmq send --topic TOPIC [--path PATH] MESSAGE...
# @summary: Publish a message through the dispatcher FIFO.
# @description: Validate the existing runtime directory, ensure the dispatcher is running, and write the message to the topic-specific bus so subscribers receive it.
# @option: -p, --path PATH    Runtime directory to target (defaults to $ZSHMQ_CTX_ROOT or /tmp/zshmq).
# @option: -T, --topic TOPIC  Topic name for the published message (required).
# @option: -d, --debug        Enable DEBUG log level.
# @option: -t, --trace        Enable TRACE log level.
# @option: -h, --help         Display command documentation and exit.
#*/

send_parser_definition() {
  zshmq_parser_defaults
  param CTX_PATH -p --path -- 'Runtime directory to target'
  param SEND_TOPIC -T --topic -- 'Explicit topic to apply'
}

send_trim() {
  # Trim leading and trailing whitespace.
  printf '%s' "$1" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

send() {
  set -eu

  if ! command -v getoptions >/dev/null 2>&1; then
    if [ -z "${ZSHMQ_ROOT:-}" ]; then
      zshmq_log_error 'send: ZSHMQ_ROOT is not set'
      return 1
    fi
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_base.sh"
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_abbr.sh"
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_help.sh"
  fi

  set +e
  zshmq_eval_parser send send_parser_definition "$@"
  status=$?
  set -e

  case $status in
    0)
      eval "set -- $ZSHMQ_REST"
      ;;
    1)
      return 1
      ;;
    2)
      return 0
      ;;
  esac

  topic=${SEND_TOPIC:-}
  if [ -z "$topic" ]; then
    zshmq_log_error 'send: --topic is required'
    return 1
  fi

  if [ $# -eq 0 ]; then
    zshmq_log_error 'send: message is required'
    return 1
  fi

  message=$1
  shift
  if [ $# -gt 0 ]; then
    message="$message $*"
  fi

  topic=$(send_trim "$topic")
  if [ -z "$topic" ]; then
    zshmq_log_error 'send: topic must not be empty'
    return 1
  fi

  body=$message

  case $topic in
    *'|'*)
      zshmq_log_error 'send: topic must not contain "|"'
      return 1
      ;;
  esac

  target=${CTX_PATH:-${ZSHMQ_CTX_ROOT:-/tmp/zshmq}}

  if [ -z "$target" ]; then
    zshmq_log_error 'send: target path is empty'
    return 1
  fi

  case $target in
    /|'')
      zshmq_log_error 'send: refusing to operate on root directory'
      return 1
      ;;
  esac

  runtime_root=${target%/}
  bus_path=${ZSHMQ_BUS:-${runtime_root}/${topic}.topic}
  pid_path=${ZSHMQ_DISPATCH_PID:-${runtime_root}/${topic}.pid}

  if [ ! -d "$target" ]; then
    zshmq_log_error 'send: runtime directory not found: %s' "$target"
    return 1
  fi

  if [ ! -p "$bus_path" ]; then
    zshmq_log_error 'send: bus FIFO not found at %s' "$bus_path"
    return 1
  fi

  if [ -f "$pid_path" ]; then
    dispatcher_pid=$(tr -d '\r\n' < "$pid_path" 2>/dev/null || :)
  else
    dispatcher_pid=
  fi

  if [ -z "$dispatcher_pid" ] || ! kill -0 "$dispatcher_pid" 2>/dev/null; then
    zshmq_log_error 'send: dispatcher is not running'
    return 1
  fi

  zshmq_log_trace 'send: topic=%s message=%s' "$topic" "$body"
  printf 'PUB|%s|%s\n' "$topic" "$body" > "$bus_path"
}

if command -v zshmq_register_command >/dev/null 2>&1; then
  zshmq_register_command send
fi

# shellcheck shell=sh

#/**
# start - Launch the dispatcher loop for zshmq.
# @usage: zshmq start --topic TOPIC [--path PATH]
# @summary: Launch the dispatcher (default root: /tmp/zshmq) in the background.
# @description: Validate an existing runtime directory created by ctx new, then spawn the dispatcher loop so publishers and subscribers can communicate via the main FIFO bus.
# @option: -p, --path PATH    Runtime directory to initialise (defaults to $ZSHMQ_CTX_ROOT or /tmp/zshmq).
# @option: -T, --topic TOPIC  Topic name handled by this dispatcher.
# @option: -f, --foreground   Run the dispatcher in the foreground.
# @option: -d, --debug        Enable DEBUG log level.
# @option: -t, --trace        Enable TRACE log level.
# @option: -h, --help         Display command documentation and exit.
#*/

start_parser_definition() {
  zshmq_parser_defaults
  param CTX_PATH -p --path -- 'Runtime directory to initialise'
  param START_TOPIC -T --topic -- 'Topic name handled by this dispatcher'
  flag START_FOREGROUND -f --foreground -- 'Run the dispatcher in the foreground'
}

dispatcher_extract_fifo_pid() {
  fifo_path=$1
  name=${fifo_path##*/}
  pid=${name##*.}
  case $pid in
    ''|*[!0-9]*)
      printf '%s\n' ''
      return 1
      ;;
  esac
  printf '%s\n' "$pid"
  return 0
}

dispatcher_prune_state() {
  state_path=$1
  tmp_state="${state_path}.dispatcher.$$"
  : > "$tmp_state"
  while IFS= read -r fifo || [ -n "$fifo" ]; do
    [ -n "$fifo" ] || continue
    fifo_pid=$(dispatcher_extract_fifo_pid "$fifo")
    if [ -n "$fifo_pid" ] && kill -0 "$fifo_pid" 2>/dev/null; then
      if [ -p "$fifo" ]; then
        printf '%s\n' "$fifo" >> "$tmp_state"
      fi
    else
      rm -f "$fifo" 2>/dev/null || :
    fi
  done < "$state_path"
  mv "$tmp_state" "$state_path"
}

zshmq_dispatch_loop() {
  bus_path=$1
  state_path=$2

  trap 'exec 3>&-; exit 0' INT TERM HUP

  # Keep the FIFO open even when no writers are connected.
  exec 3<>"$bus_path"

  while IFS= read -r line <&3; do
    case $line in
      SUB\|*)
        entry=${line#SUB|}
        if [ -n "$entry" ]; then
          [ -f "$state_path" ] || : > "$state_path"
          if ! grep -F -- "$entry" "$state_path" >/dev/null 2>&1; then
            printf '%s\n' "$entry" >> "$state_path"
          fi
        fi
        ;;
      UNSUB\|*)
        entry=${line#UNSUB|}
        if [ -n "$entry" ] && [ -f "$state_path" ]; then
          tmp_state="${state_path}.tmp.$$"
          : > "$tmp_state"
          while IFS= read -r state_line || [ -n "$state_line" ]; do
            [ "$state_line" = "$entry" ] && continue
            printf '%s\n' "$state_line" >> "$tmp_state"
          done < "$state_path"
          mv "$tmp_state" "$state_path"
        fi
        ;;
      PUB\|*)
        payload=${line#PUB|}
        topic=${payload%%|*}
        message=${payload#*|}
        if [ -f "$state_path" ] && [ -n "$topic" ]; then
          message_body=$message
          if [ -s "$state_path" ]; then
            dispatcher_prune_state "$state_path"
          fi
          zshmq_log_trace 'dispatcher: topic=%s message=%s' "$topic" "$message_body"
          while IFS= read -r fifo_path || [ -n "$fifo_path" ]; do
            [ -n "$fifo_path" ] || continue
            fifo_pid=$(dispatcher_extract_fifo_pid "$fifo_path")
            if [ -z "$fifo_pid" ] || ! kill -0 "$fifo_pid" 2>/dev/null; then
              continue
            fi
            case $fifo_path in
              *)
                if [ -p "$fifo_path" ]; then
                  zshmq_log_trace 'dispatcher: deliver topic=%s message=%s fifo=%s' "$topic" "$message_body" "$fifo_path"
                  { printf '%s\n' "$message_body"; } >> "$fifo_path" 2>/dev/null || :
                fi
                ;;
            esac
          done < "$state_path"
        fi
        ;;
      *)
        :
        ;;
    esac
  done
}

start() {
  set -eu

  if ! command -v getoptions >/dev/null 2>&1; then
    if [ -z "${ZSHMQ_ROOT:-}" ]; then
      zshmq_log_error 'start: ZSHMQ_ROOT is not set'
      return 1
    fi
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_base.sh"
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_abbr.sh"
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_help.sh"
  fi

  unset START_FOREGROUND ||:

  set +e
  zshmq_eval_parser start start_parser_definition "$@"
  status=$?
  set -e

  case $status in
    0)
      eval "set -- $ZSHMQ_REST"
      ;;
    1)
      return 1
      ;;
    2)
      return 0
      ;;
  esac

  if [ $# -gt 0 ]; then
    zshmq_log_error 'start: unexpected argument -- %s' "$1"
    return 1
  fi

  unset ZSHMQ_REST ||:

  topic=${START_TOPIC:-}
  if [ -z "$topic" ]; then
    zshmq_log_error 'start: --topic is required'
    return 1
  fi

  target=${CTX_PATH:-${ZSHMQ_CTX_ROOT:-/tmp/zshmq}}

  if [ -z "$target" ]; then
    zshmq_log_error 'start: target path is empty'
    return 1
  fi

  case $target in
    /|'')
      zshmq_log_error 'start: refusing to operate on root directory'
      return 1
      ;;
  esac

  runtime_root=${target%/}
  state_path=${ZSHMQ_STATE:-${runtime_root}/${topic}.state}
  bus_path=${ZSHMQ_BUS:-${runtime_root}/${topic}.topic}
  pid_path=${ZSHMQ_DISPATCH_PID:-${runtime_root}/${topic}.pid}

  if [ ! -d "$target" ]; then
    zshmq_log_error 'start: runtime directory not found: %s' "$target"
    return 1
  fi

  if [ ! -p "$bus_path" ]; then
    zshmq_log_error 'start: bus FIFO not found at %s' "$bus_path"
    return 1
  fi

  if [ ! -f "$state_path" ]; then
    zshmq_log_error 'start: state file not found at %s' "$state_path"
    return 1
  fi

  if [ -f "$pid_path" ]; then
    existing_pid=$(tr -d '\r\n' < "$pid_path" 2>/dev/null || :)
    if [ -n "$existing_pid" ] && kill -0 "$existing_pid" 2>/dev/null; then
      zshmq_log_debug 'start: dispatcher already running (pid=%s)' "$existing_pid"
      return 1
    fi
    rm -f "$pid_path"
  fi

  if [ "${START_FOREGROUND:-0}" = "1" ]; then
    zshmq_dispatch_loop "$bus_path" "$state_path" &
    dispatcher_pid=$!
    printf '%s\n' "$dispatcher_pid" > "$pid_path"
    zshmq_log_debug 'Dispatcher started (pid=%s)' "$dispatcher_pid"

    start_foreground_cleaned=0

    start_foreground_cleanup() {
      if [ "${start_foreground_cleaned}" -eq 1 ]; then
        return 0
      fi
      start_foreground_cleaned=1
      trap - INT TERM HUP EXIT
      if [ -n "${dispatcher_pid:-}" ] && kill -0 "$dispatcher_pid" 2>/dev/null; then
        kill "$dispatcher_pid" 2>/dev/null || :
        wait "$dispatcher_pid" 2>/dev/null || :
      else
        wait "$dispatcher_pid" 2>/dev/null || :
      fi
      rm -f "$pid_path"
    }

    trap 'start_foreground_cleanup; exit 130' INT
    trap 'start_foreground_cleanup; exit 143' TERM
    trap 'start_foreground_cleanup; exit 129' HUP
    trap 'start_foreground_cleanup' EXIT

    wait "$dispatcher_pid"
    wait_status=$?
    start_foreground_cleanup
    return "$wait_status"
  fi

  zshmq_dispatch_loop "$bus_path" "$state_path" &
  dispatcher_pid=$!
  printf '%s\n' "$dispatcher_pid" > "$pid_path"
  zshmq_log_debug 'Dispatcher started (pid=%s)' "$dispatcher_pid"
}

if command -v zshmq_register_command >/dev/null 2>&1; then
  zshmq_register_command start
fi

# shellcheck shell=sh

#/**
# stop - Terminate the zshmq dispatcher loop.
# @usage: zshmq stop [--path PATH]
# @summary: Stop the dispatcher running for the given runtime directory (default: /tmp/zshmq).
# @description: Read the dispatcher PID from the runtime directory, send it SIGTERM, and remove the PID file once the dispatcher exits.
# @option: -p, --path PATH    Runtime directory to target (defaults to $ZSHMQ_CTX_ROOT or /tmp/zshmq).
# @option: -d, --debug        Enable DEBUG log level.
# @option: -t, --trace        Enable TRACE log level.
# @option: -h, --help         Display command documentation and exit.
#*/

stop_parser_definition() {
  zshmq_parser_defaults
  param CTX_PATH -p --path -- 'Runtime directory to target'
}

stop() {
  set -eu

  if ! command -v getoptions >/dev/null 2>&1; then
    if [ -z "${ZSHMQ_ROOT:-}" ]; then
      zshmq_log_error 'stop: ZSHMQ_ROOT is not set'
      return 1
    fi
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_base.sh"
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_abbr.sh"
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_help.sh"
  fi

  set +e
  zshmq_eval_parser stop stop_parser_definition "$@"
  status=$?
  set -e

  case $status in
    0)
      eval "set -- $ZSHMQ_REST"
      ;;
    1)
      return 1
      ;;
    2)
      return 0
      ;;
  esac

  if [ $# -gt 0 ]; then
    zshmq_log_error 'stop: unexpected argument -- %s' "$1"
    return 1
  fi

  unset ZSHMQ_REST ||:

  target=${CTX_PATH:-${ZSHMQ_CTX_ROOT:-/tmp/zshmq}}

  if [ -z "$target" ]; then
    zshmq_log_error 'stop: target path is empty'
    return 1
  fi

  case $target in
    /|'')
      zshmq_log_error 'stop: refusing to operate on root directory'
      return 1
      ;;
  esac

  runtime_root=${target%/}
  pid_path=${ZSHMQ_DISPATCH_PID:-${runtime_root}/bus.pid}

  if [ ! -f "$pid_path" ]; then
    zshmq_log_debug 'Dispatcher is not running.'
    return 0
  fi

  dispatcher_pid=$(tr -d '\r\n' < "$pid_path" 2>/dev/null || :)
  if [ -z "$dispatcher_pid" ]; then
    rm -f "$pid_path"
    zshmq_log_debug 'Dispatcher is not running.'
    return 0
  fi

  if ! kill -0 "$dispatcher_pid" 2>/dev/null; then
    rm -f "$pid_path"
    zshmq_log_debug 'Dispatcher is not running.'
    return 0
  fi

  kill "$dispatcher_pid" 2>/dev/null || :

  for attempt in 1 2 3 4 5; do
    if ! kill -0 "$dispatcher_pid" 2>/dev/null; then
      break
    fi
    sleep 1
  done

  if kill -0 "$dispatcher_pid" 2>/dev/null; then
    zshmq_log_error 'stop: dispatcher (pid=%s) did not terminate' "$dispatcher_pid"
    return 1
  fi

  rm -f "$pid_path"
  zshmq_log_debug 'Dispatcher stopped (pid=%s)' "$dispatcher_pid"
}

if command -v zshmq_register_command >/dev/null 2>&1; then
  zshmq_register_command stop
fi

# shellcheck shell=sh

#/**
# sub - Subscribe to messages for a specific topic.
# @usage: zshmq sub --topic TOPIC [--path PATH]
# @summary: Register a subscriber FIFO and stream dispatched messages for TOPIC.
# @description: Validate the runtime directory, ensure the dispatcher is running, register the subscription with the dispatcher, and stream messages until interrupted.
# @option: -p, --path PATH    Runtime directory to target (defaults to $ZSHMQ_CTX_ROOT or /tmp/zshmq).
# @option: -T, --topic TOPIC  Topic name to subscribe to.
# @option: -d, --debug        Enable DEBUG log level.
# @option: -t, --trace        Enable TRACE log level.
# @option: -h, --help         Display command documentation and exit.
#*/

sub_parser_definition() {
  zshmq_parser_defaults
  param CTX_PATH -p --path -- 'Runtime directory to target'
  param SUB_TOPIC -T --topic -- 'Topic name to subscribe to'
}

sub_extract_fifo_pid() {
  fifo_path=$1
  name=${fifo_path##*/}
  pid=${name##*.}
  case $pid in
    ''|*[!0-9]*)
      printf '%s\n' ''
      return 1
      ;;
  esac
  printf '%s\n' "$pid"
  return 0
}

sub_prune_state() {
  state_path=$1
  tmp_state="${state_path}.prune.$$"
  : > "$tmp_state"
  while IFS= read -r existing_fifo || [ -n "$existing_fifo" ]; do
    [ -n "$existing_fifo" ] || continue
    fifo_pid=$(sub_extract_fifo_pid "$existing_fifo")
    if [ -n "$fifo_pid" ] && kill -0 "$fifo_pid" 2>/dev/null; then
      if [ -p "$existing_fifo" ]; then
        printf '%s\n' "$existing_fifo" >> "$tmp_state"
      fi
    else
      rm -f "$existing_fifo" 2>/dev/null || :
    fi
  done < "$state_path"
  mv "$tmp_state" "$state_path"
}

sub_cleanup() {
  if [ "${SUB_CLEANED:-0}" -eq 1 ]; then
    return 0
  fi
  SUB_CLEANED=1

  if [ -n "${SUB_FIFO_FD:-}" ]; then
    eval "exec ${SUB_FIFO_FD}>&-" 2>/dev/null || :
  fi

  if [ "${SUB_REGISTERED:-0}" -eq 1 ] && [ -n "${SUB_BUS_PATH:-}" ] && [ -n "${SUB_FIFO_PATH:-}" ]; then
    if [ -n "${SUB_DISPATCHER_PID:-}" ] && kill -0 "$SUB_DISPATCHER_PID" 2>/dev/null; then
      { printf 'UNSUB|%s\n' "$SUB_FIFO_PATH"; } > "$SUB_BUS_PATH" 2>/dev/null || :
    fi
    SUB_REGISTERED=0
  fi

  if [ -n "${SUB_STATE_PATH:-}" ] && [ -f "${SUB_STATE_PATH:-}" ]; then
    tmp_state="${SUB_STATE_PATH}.tmp.$$"
    : > "$tmp_state"
    while IFS= read -r state_line || [ -n "$state_line" ]; do
      [ -n "$state_line" ] || continue
      state_fifo=$state_line
      if [ "$state_fifo" = "${SUB_FIFO_PATH:-}" ]; then
        rm -f "$state_fifo" 2>/dev/null || :
        continue
      fi
      fifo_pid=$(sub_extract_fifo_pid "$state_fifo")
      if [ -n "$fifo_pid" ] && kill -0 "$fifo_pid" 2>/dev/null; then
        if [ -p "$state_fifo" ]; then
          printf '%s\n' "$state_fifo" >> "$tmp_state"
        fi
      else
        rm -f "$state_fifo" 2>/dev/null || :
      fi
    done < "${SUB_STATE_PATH}"
    mv "$tmp_state" "${SUB_STATE_PATH}"
  fi

  if [ -n "${SUB_FIFO_PATH:-}" ] && [ -e "$SUB_FIFO_PATH" ]; then
    rm -f "$SUB_FIFO_PATH" 2>/dev/null || :
  fi
}

sub() {
  set -eu

  if ! command -v getoptions >/dev/null 2>&1; then
    if [ -z "${ZSHMQ_ROOT:-}" ]; then
      zshmq_log_error 'sub: ZSHMQ_ROOT is not set'
      return 1
    fi
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_base.sh"
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_abbr.sh"
    # shellcheck disable=SC1090
    . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_help.sh"
  fi

  set +e
  zshmq_eval_parser sub sub_parser_definition "$@"
  status=$?
  set -e

  case $status in
    0)
      eval "set -- $ZSHMQ_REST"
      ;;
    1)
      return 1
      ;;
    2)
      return 0
      ;;
  esac

  if [ $# -gt 0 ]; then
    zshmq_log_error 'sub: unexpected argument -- %s' "$1"
    return 1
  fi

  topic=${SUB_TOPIC:-}
  if [ -z "$topic" ]; then
    zshmq_log_error 'sub: --topic is required'
    return 1
  fi

  target=${CTX_PATH:-${ZSHMQ_CTX_ROOT:-/tmp/zshmq}}

  if [ -z "$target" ]; then
    zshmq_log_error 'sub: target path is empty'
    return 1
  fi

  case $target in
    /|'')
      zshmq_log_error 'sub: refusing to operate on root directory'
      return 1
      ;;
  esac

  if [ ! -d "$target" ]; then
    zshmq_log_error 'sub: runtime directory not found: %s' "$target"
    return 1
  fi

  runtime_root=${target%/}
  state_path=${ZSHMQ_STATE:-${runtime_root}/${topic}.state}
  bus_path=${ZSHMQ_BUS:-${runtime_root}/${topic}.topic}
  pid_path=${ZSHMQ_DISPATCH_PID:-${runtime_root}/${topic}.pid}

  if [ ! -f "$state_path" ]; then
    zshmq_log_error 'sub: state file not found at %s' "$state_path"
    return 1
  fi

  if [ ! -p "$bus_path" ]; then
    zshmq_log_error 'sub: bus FIFO not found at %s' "$bus_path"
    return 1
  fi

  if [ ! -f "$pid_path" ]; then
    zshmq_log_error 'sub: dispatcher pid file not found at %s' "$pid_path"
    return 1
  fi

  dispatcher_pid=$(tr -d '\r\n' < "$pid_path" 2>/dev/null || :)
  if [ -z "$dispatcher_pid" ] || ! kill -0 "$dispatcher_pid" 2>/dev/null; then
    zshmq_log_error 'sub: dispatcher is not running'
    return 1
  fi

  SUB_DISPATCHER_PID=$dispatcher_pid

  fifo_path=${runtime_root}/${topic}.$$
  if [ -e "$fifo_path" ]; then
    zshmq_log_error 'sub: subscriber fifo already exists at %s' "$fifo_path"
    return 1
  fi

  if ! mkfifo "$fifo_path"; then
    zshmq_log_error 'sub: failed to create fifo at %s' "$fifo_path"
    return 1
  fi

  SUB_BUS_PATH=$bus_path
  SUB_FIFO_PATH=$fifo_path
  SUB_FIFO_FD=9
  SUB_CLEANED=0
  SUB_REGISTERED=0
  SUB_STATE_PATH=$state_path

  if [ -s "$state_path" ]; then
    sub_prune_state "$state_path"
  fi

  trap 'sub_cleanup; exit 130' INT
  trap 'sub_cleanup; exit 143' TERM
  trap 'sub_cleanup; exit 129' HUP
  trap 'sub_cleanup' EXIT

  if ! { printf 'SUB|%s\n' "$fifo_path"; } > "$bus_path"; then
    zshmq_log_error 'sub: failed to register with dispatcher'
    sub_cleanup
    return 1
  fi
  SUB_REGISTERED=1

  if ! exec 9<>"$fifo_path"; then
    zshmq_log_error 'sub: unable to open fifo for reading'
    sub_cleanup
    return 1
  fi

  zshmq_log_debug 'sub: subscribed to topic=%s fifo=%s' "$topic" "$fifo_path"

  while IFS= read -r line <&9 || [ -n "$line" ]; do
    zshmq_log_trace 'sub: received topic=%s message=%s' "$topic" "$line"
    printf '%s\n' "$line"
  done

  sub_cleanup
}

if command -v zshmq_register_command >/dev/null 2>&1; then
  zshmq_register_command sub
fi

# shellcheck shell=sh

#/**
# topic - Manage topic assets within a runtime directory.
# @usage: zshmq topic <command> [options]
# @summary: Manage topic FIFOs and state files.
# @description: Provides subcommands to provision or remove the FIFO/state pair used by publishers and subscribers for a topic.
# @option: -p, --path PATH    Runtime directory to target (defaults to $ZSHMQ_CTX_ROOT or /tmp/zshmq).
# @option: -d, --debug        Enable DEBUG log level.
# @option: -t, --trace        Enable TRACE log level.
# @option: -h, --help         Display command documentation and exit.
#*/

topic_print_usage() {
  printf '%s\n' 'Usage: zshmq topic <command> [options]'
  printf '%s\n' ''
  printf '%s\n' 'Commands:'
  printf '  new      Initialise topic assets (-T/--topic required)\n'
  printf '  destroy  Remove topic assets    (-T/--topic required)\n'
}

topic_require_topic() {
  subcommand=$1
  shift

  topic_name=

  while [ $# -gt 0 ]; do
    case $1 in
      -T|--topic)
        shift
        if [ $# -eq 0 ]; then
          zshmq_log_error 'topic %s: --topic requires a value' "$subcommand"
          return 1
        fi
        topic_name=$1
        ;;
      -T=*|--topic=*)
        topic_name=${1#*=}
        ;;
      --)
        shift
        break
        ;;
      -*)
        zshmq_log_error 'topic %s: unexpected option -- %s' "$subcommand" "$1"
        return 1
        ;;
      *)
        zshmq_log_error 'topic %s: unexpected argument -- %s' "$subcommand" "$1"
        return 1
        ;;
    esac
    shift
  done

  if [ $# -gt 0 ]; then
    zshmq_log_error 'topic %s: unexpected argument -- %s' "$subcommand" "$1"
    return 1
  fi

  if [ -z "${topic_name:-}" ]; then
    zshmq_log_error 'topic %s: --topic is required' "$subcommand"
    return 1
  fi

  case $topic_name in
    *'|'*)
      zshmq_log_error 'topic %s: topic must not contain "|"' "$subcommand"
      return 1
      ;;
    *'/'*)
      zshmq_log_error 'topic %s: topic must not contain "/"' "$subcommand"
      return 1
      ;;
    *'
'*)
      zshmq_log_error 'topic %s: topic must not contain newlines' "$subcommand"
      return 1
      ;;
  esac

  printf '%s\n' "$topic_name"
}

topic_ensure_runtime() {
  path=$1

  if [ -z "$path" ]; then
    zshmq_log_error 'topic: target path is empty'
    return 1
  fi

  case $path in
    /|'')
      zshmq_log_error 'topic: refusing to operate on root directory'
      return 1
      ;;
  esac

  if [ ! -d "$path" ]; then
    zshmq_log_error 'topic: runtime directory not found: %s' "$path"
    return 1
  fi

  printf '%s\n' "${path%/}"
}

topic_new() {
  runtime_root=$1
  topic_name=$2

  state_path=${ZSHMQ_STATE:-${runtime_root}/${topic_name}.state}
  bus_path=${ZSHMQ_BUS:-${runtime_root}/${topic_name}.topic}

  case $state_path in
    */*)
      state_dir=${state_path%/*}
      ;;
    *)
      state_dir=.
      ;;
  esac
  if [ "$state_dir" != "." ] && [ ! -d "$state_dir" ]; then
    mkdir -p "$state_dir"
  fi

  if [ -e "$state_path" ] && [ ! -f "$state_path" ]; then
    zshmq_log_error 'topic new: state path is not a regular file: %s' "$state_path"
    return 1
  fi
  : > "$state_path"

  case $bus_path in
    */*)
      bus_dir=${bus_path%/*}
      ;;
    *)
      bus_dir=.
      ;;
  esac
  if [ "$bus_dir" != "." ] && [ ! -d "$bus_dir" ]; then
    mkdir -p "$bus_dir"
  fi

  if [ -e "$bus_path" ]; then
    if [ -p "$bus_path" ]; then
      rm -f "$bus_path"
    else
      zshmq_log_error 'topic new: bus path is not a FIFO: %s' "$bus_path"
      return 1
    fi
  fi

  if ! mkfifo "$bus_path"; then
    zshmq_log_error 'topic new: failed to create fifo at %s' "$bus_path"
    return 1
  fi

  zshmq_log_debug 'topic new: initialised topic=%s runtime=%s' "$topic_name" "$runtime_root"
}

topic_destroy() {
  runtime_root=$1
  topic_name=$2

  state_path=${ZSHMQ_STATE:-${runtime_root}/${topic_name}.state}
  bus_path=${ZSHMQ_BUS:-${runtime_root}/${topic_name}.topic}

  if [ -f "$state_path" ]; then
    rm -f "$state_path"
    zshmq_log_debug 'topic destroy: removed state=%s' "$state_path"
  else
    zshmq_log_trace 'topic destroy: state missing (%s)' "$state_path"
  fi

  if [ -p "$bus_path" ] || [ -f "$bus_path" ]; then
    rm -f "$bus_path"
    zshmq_log_debug 'topic destroy: removed fifo=%s' "$bus_path"
  else
    zshmq_log_trace 'topic destroy: fifo missing (%s)' "$bus_path"
  fi
}

topic() {
  set -eu

  log_level=${ZSHMQ_LOG_LEVEL:-INFO}
  target_path=${ZSHMQ_CTX_ROOT:-/tmp/zshmq}

  export ZSHMQ_LOG_LEVEL=$log_level

  while [ $# -gt 0 ]; do
    case $1 in
      -p|--path)
        shift
        if [ $# -eq 0 ]; then
          zshmq_log_error 'topic: --path requires a value'
          return 1
        fi
        target_path=$1
        ;;
      -p=*|--path=*)
        target_path=${1#*=}
        ;;
      -d|--debug)
        log_level=DEBUG
        ;;
      -t|--trace)
        log_level=TRACE
        ;;
      -h|--help|help)
        topic_print_usage
        return 0
        ;;
      --)
        shift
        break
        ;;
      -*)
        zshmq_log_error 'topic: unexpected option -- %s' "$1"
        return 1
        ;;
      *)
        break
        ;;
    esac
    shift || :
  done

  export ZSHMQ_LOG_LEVEL=$log_level

  if [ $# -eq 0 ]; then
    topic_print_usage
    return 1
  fi

  subcommand=$1
  shift

  runtime_root=$(topic_ensure_runtime "$target_path") || return 1

  case $subcommand in
    new)
      topic_name=$(topic_require_topic "$subcommand" "$@") || return 1
      topic_new "$runtime_root" "$topic_name"
      ;;
    destroy)
      topic_name=$(topic_require_topic "$subcommand" "$@") || return 1
      topic_destroy "$runtime_root" "$topic_name"
      ;;
    -h|--help|help)
      topic_print_usage
      return 0
      ;;
    *)
      zshmq_log_error 'topic: unknown command -- %s' "$subcommand"
      topic_print_usage
      return 1
      ;;
  esac
}

if command -v zshmq_register_command >/dev/null 2>&1; then
  zshmq_register_command topic
fi

set -eu

script_dir=$(
  CDPATH= cd -- "$(dirname -- "$0")" && pwd
)
if [ -n "${ZSHMQ_EMBEDDED:-}" ]; then
  ZSHMQ_ROOT=${script_dir}
else
  ZSHMQ_ROOT=$(
    CDPATH= cd -- "${script_dir}/.." && pwd
  )
fi
export ZSHMQ_ROOT
export ZSHMQ_VERSION=${ZSHMQ_VERSION:-$( [ -f "${ZSHMQ_ROOT}/VERSION" ] && cat "${ZSHMQ_ROOT}/VERSION" || printf '%s\n' '0.0.1' )}

if [ -z "${ZSHMQ_EMBEDDED:-}" ]; then
  # Load getoptions once so command implementations can rely on it.
  # shellcheck disable=SC1090
  . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_base.sh"
  # shellcheck disable=SC1090
  . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_abbr.sh"
  # shellcheck disable=SC1090
  . "${ZSHMQ_ROOT}/vendor/getoptions/lib/getoptions_help.sh"
  # shellcheck disable=SC1091
  . "${ZSHMQ_ROOT}/lib/command_helpers.sh"
  # shellcheck disable=SC1091
  . "${ZSHMQ_ROOT}/lib/logging.sh"

  # Load command implementations after helper definitions.
  # shellcheck disable=SC1091
  . "${ZSHMQ_ROOT}/lib/ctx.sh"
  # shellcheck disable=SC1091
  . "${ZSHMQ_ROOT}/lib/topic.sh"
  # shellcheck disable=SC1091
  . "${ZSHMQ_ROOT}/lib/start.sh"
  # shellcheck disable=SC1091
  . "${ZSHMQ_ROOT}/lib/stop.sh"
  # shellcheck disable=SC1091
  . "${ZSHMQ_ROOT}/lib/send.sh"
  # shellcheck disable=SC1091
  . "${ZSHMQ_ROOT}/lib/sub.sh"
fi

zshmq_command_list() {
  if [ -n "${ZSHMQ_COMMAND_REGISTRY:-}" ]; then
    zshmq_registered_commands
    return
  fi

  for path in "${ZSHMQ_ROOT}/lib"/*.sh; do
    [ -f "$path" ] || continue
    cmd=${path##*/}
    cmd=${cmd%.sh}
    [ "$cmd" = "command_helpers" ] && continue
    [ "$cmd" = "logging" ] && continue
    printf '%s\n' "$cmd"
  done
}

zshmq_show_command_help() {
  cmd=$1
  zshmq_command_file "$cmd" >/dev/null 2>&1 || {
    printf 'Unknown command: %s\n' "$cmd"
    return 1
  }
  zshmq_print_command_help "$cmd"
}

zshmq_show_help() {
  printf '%s\n' 'Zero Shell Message Queue (zshmq)'
  printf '%s\n' ''
  printf '%s\n' 'Usage: zshmq <command> [options]'
  printf '%s\n' ''
  printf '%s\n' 'Commands:'
  for cmd in $(zshmq_command_list); do
    summary=$(zshmq_command_summary "$cmd")
    printf '  %s - %s\n' "$cmd" "$summary"
  done
  printf '\n'
  printf '%s\n' 'Each command supports -h/--help plus -d/--debug and -t/--trace for log verbosity.'
  printf '%s\n' 'Run `zshmq help <command>` or `zshmq <command> --help` for command-specific documentation.'
}

if [ $# -eq 0 ]; then
  zshmq_show_help
  exit 0
fi

command_name=$1
shift

case $command_name in
  -h|--help|help)
    if [ $# -eq 0 ]; then
      zshmq_show_help
    else
      help_target=$1
      zshmq_show_command_help "$help_target"
    fi
    exit 0
    ;;
  --version)
    printf '%s\n' "${ZSHMQ_VERSION:-0.0.0}"
    exit 0
    ;;
  ctx)
    ctx "$@"
    ;;
  topic)
    topic "$@"
    ;;
  start)
    start "$@"
    ;;
  stop)
    stop "$@"
    ;;
  send)
    send "$@"
    ;;
  sub)
    sub "$@"
    ;;
  *)
    printf 'zshmq: unknown command -- %s\n' "$command_name" >&2
    printf '%s\n' '' >&2
    zshmq_show_help >&2
    exit 1
    ;;
 esac
